development:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: heads-up-poker_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:pc7bfd9a4468f39f94174fcdd6f6d4c191e12e332f91d71edf4a42176b9df848c@ec2-34-236-65-51.compute-1.amazonaws.com:63539
  channel_prefix: heads-up-poker_production
