development:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: heads-up-poker_production

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: heads-up-poker_production
