default: &default
  adapter: postgresql
  pool: 5
  # 以下の3つを追加
  #username: poker
  #password: 62435a4674a10ee8ff3f5ea5
  # RailsサーバとPostgreSQLサーバが同じ場合
  # host: localhost
development:
  <<: *default
  database: poker_development
test:
  <<: *default
  database: poker_test